### PR TITLE
Update repository url.

### PR DESCRIPTION
**Pull request by DylanPiercey**

### CODE REVIEW

**Comment by alexindigo** [comment]
There is #140 :)

**Comment by DylanPiercey** [comment]
Ah, my bad. Although shouldn't the url be the repository url not the ".git"?

https://docs.npmjs.com/files/package.json#repository

**Comment by alexindigo** [comment]
This is what the book says: "The URL should be a publicly available (perhaps read-only) url that can be handed directly to a VCS program without any modification."

**Comment by DylanPiercey** [comment]
Alrighty, I wasn't sure anyway. Just seems most of the examples use the https url.

**Comment by alexindigo** [comment]
Yep, their examples out of sync with the text :) https does work with github though, but others like Stash having hard time with it. So it's just habit to put the right protocol there.

**Comment by DylanPiercey** [comment]
Interesting. Thanks for the heads up!

Closing this.

**Pull request closed without merging**
