### PR TITLE
fix: move util.isArray to Array.isArray

### PR DESCRIPTION
**Pull request by marco-ippolito**
Fixes: https://github.com/form-data/form-data/issues/563

### CODE REVIEW

**Comment by Agnostic** [comment]
Any update on this?

**Comment by webaddicto** [comment]
We're getting the deprecation warning too with NodeJs 22.

Any possible update when this will be merged?

It was reported a few months ago on Jun 11 (same fix) but still not merged:
https://github.com/form-data/form-data/pull/558

**Comment by skgith1** [comment]
Any updates?

**Comment by gzurbach** [comment]
@niftylettuce do you have permissions to merge this PR and publish it as `v4.0.1`?

**Review by ljharb — APPROVED** [review]

**Comment by vamshi1100** [comment]
(node:19152) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead. where to use

**Comment by vamshi1100** [comment]
where to use array.isarray()

**Comment by ljharb** [comment]
@jkoenig134 i'll be publishing it as soon as i'm given publish access.

**Comment by jkoenig134** [comment]
> @jkoenig134 i'll be publishing it as soon as i'm given publish access.

Awesome, thanks for the information!

**Pull request merged**
