### PR TITLE
Fix for browserify

### PR DESCRIPTION
**Pull request by jwulf**

### CODE REVIEW

**Comment by alexindigo** [comment]
Shouldn't browserify use `browser` field of package.json?

@DylanPiercey Hey, you're browserify guy, can you take a look? 
Thank you.

**Comment by DylanPiercey** [comment]
@jwulf, what exactly does this fix? Firstly file extensions AFAIK are optional in package.json and second browserify will use the browser field?

**Comment by jwulf** [comment]
The extensions are optional, and it operates fine in a node.js environment without it. Using node.js 4.0 and browserify to pack up winston, however, fails when the extension is not present (it will insert the entire path into the bundle, rather the actual code that it references), or when a relative path is specified.

**Comment by alexindigo** [comment]
@jwulf Correct me if I'm wrong. If `browser` field is present in `package..json` it will be used **instead of** `main` field, right?  

And do you mind to elaborate on "insert the entire path into the bundle, rather the actual code", thank you.

PS. AFAIK resolution of the module path done using node's built-in mechanism (same as `require` function) and hasn't changed with node 4.0. So if you see different behavior maybe it's a bug inbrowserify and/or node itself?

**Comment by alexindigo** [comment]
Seems like no longer the issue. Closing. Please feel free to continue discussion.

**Pull request closed without merging**
